### PR TITLE
Use `sesame.paths` instead of `sesame.path`

### PR DESCRIPTION
**Pull request by andromedarabbit**
- Support multiple combination of `path` and `depth`

### CODE REVIEW

**Comment by gerardroche** [comment]
Renaming **path** to **paths** is not backwards compatible. 

An alternative solution would be to make **sesame.depth** accept a separator like **sesame.path**:

**sesame.path** works similar to the system environment **PATH** variable which accepts multiple paths by using a **PATH** separator e.g. `"~/projects:~/work:~/src"`, so we could do the same for **sesame.depth** i.e. set depth to "1:2:1" to indicate a depth for each path. 

If there is a mismatch e.g. path `"~/projects:~/work:~/src"` and depth `"1:2"`, then set a depth of **2** for the remaining paths i.e. the last two paths. If there's a mismatch the other direction e.g. path `"~/projects:~/work"` and depth `"1:2:3"` print a notice or warning, but it should still work ok.

The other alternative would be to not rename **sesame.path** to **sesame.paths** and instead inspect the type of the setting **sesame.path**: if it's a list then the structure is like you propose, if not then it should be string a work like it does now. So the user can use a string or list to set the paths. 

I think **sesame.depth** should still at least work as a string with a separator, so that the user has the option of using strings. One reason is that you can use a **PROJECT_PATH** environment variable to set the projects path, and environment variables can only be strings.

**Comment by andromedarabbit** [comment]
@gerardroche You have a point. I will let you know once the patch is ready. Thanks for the feedback!

**Comment by gerardroche** [comment]
I've been thinking about it more. Maybe put it on hold for a moment. I might be able to get done later this evening. I'm thinking about the following:

* Relevant commands like the sesame_open should accept any of the options so that users can create custom commands and specify any settings too
* `path` can accept:
  - a string, which can use PATH separator to specify multiple paths
  - a list, which can contain strings (will accept PATH separator too) or dicts which require at least "path" key (will accept PATH separator too), and other setting that will override any default or user global value e.g. if the user set `sesame.depth` or will fallback to the the package default.

After thinking thing about it, allowing settings like depth accept a separator e.g. `"1:2:3"` doesn't really make sense because we'd have to do that with all the settings. I think the way you were doing it was correct i.e. if you need to configure paths individually you use the list+dict format for the **path** setting.

In terms of renaming **path** to **paths**. I'm a little bit on the fence. Either way, we can make a decision on renaming the setting last, and before v2.0.

**Comment by gerardroche** [comment]
How does does this work for you? See https://github.com/gerardroche/sublime-sesame/blob/master/README.md

**Comment by andromedarabbit** [comment]
It works perfectly. Thanks!

**Pull request closed without merging**
